name: Coverage

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci
  BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}
  BASESCAN_API_KEY: ${{secrets.BASESCAN_API_KEY}}

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-e52076714ace23c7a68e14f0048a40be3c6c8f0b

      # https://twitter.com/PaulRBerg/status/1611116650664796166
      - name: Generate fuzz seed with 1 day TTL
        run: |
          echo "FOUNDRY_FUZZ_SEED=$(( $(date +%s) - $(date +%s) % 86400 ))" >> $GITHUB_ENV

      - name: Run coverage (USDC)
        env:
          TS_NODE_TRANSPILE_ONLY: "1"
        run: |
          export ASSET_CONFIG_PATH="config/strategies/USDCStrategyConfig.json"
          forge coverage \
            --fork-url base \
            --ffi \
            --report summary \
            --report lcov \
            --report-file lcov.info \
            --skip s.sol \
            --ir-minimum \
            --allow-failure \
            --compute-units-per-second 150 \
            --fork-retries 10 \
            --fork-retry-backoff 500

      # To ignore coverage for certain directories modify the paths in this step as needed.
      # The below default ignores coverage results for the test and script directories.
      # Disable branch coverage temporarily due to https://github.com/foundry-rs/foundry/issues/8279
      - name: Filter directories
        run: |
          sudo apt update && sudo apt install -y lcov
          lcov --remove lcov.info 'test/*' 'script/*' --output-file lcov.info --rc lcov_branch_coverage=0

      - name: Generate HTML report
        run: |
          genhtml lcov.info --output-dir coverage

      # This step posts a detailed coverage report as a comment and deletes previous comments on
      # each push. The below step is used to fail coverage if the specified coverage threshold is
      # not met.
      - name: Post coverage report
        if: github.event_name == 'pull_request' # This action fails when ran outside of a pull request.
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          delete-old-comments: true
          lcov-file: ./lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }} # Adds a coverage summary comment to the PR.

      # - name: Verify minimum coverage
      #   uses: zgosalvez/github-actions-report-lcov@v2
      #   with:
      #     coverage-files: ./lcov.info
      #     minimum-coverage: 90

      # Upload coverage artifacts
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: |
            lcov.info
            coverage/
